---
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.dotfiles
  tasks:
    - include: tasks/main.yml
