---
- name: Install Atom for Linux
  yum:
    name: atom
    state: latest
  become: true
  when: ansible_facts['distribution'] == "Fedora"

- name: Check installed Atom packages
  shell: apm list --packages --installed --enabled --bare --versions=false
  register: atom_installed_packages
  changed_when: false

- name: Install Atom packages
  shell: apm install {{ item }}
  with_items: "{{ atom_packages }}"
  when: item not in atom_installed_packages.stdout_lines
