---
- block:
  - name: Uninstall Podman
    dnf:
      name: podman
      state: removed
    become: true

  - name: Add Docker RPM repository for Fedora
    command:
      cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      warn: false
    args:
      creates: /etc/yum.repos.d/docker-ce.repo
    become: true

  - name: Install Docker and Hadolint for Fedora
    dnf:
      name: "{{ item }}"
      state: latest
    become: true
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - hadolint

  - name: Make sure Docker is running
    service:
      name: docker
      state: started
    become: true
  when: ansible_facts['distribution'] == "Fedora"

- block:
  - name: Install Docker for MacOS
    homebrew_cask:
      name: docker
      state: present

  - name: Install Hadolint for MacOS
    homebrew:
      name: hadolint
      state: present
  when: ansible_facts['os_family'] == "Darwin"
