---
- name: Check installed Terraform versions
  shell: tfenv list
  register: terraform_installed
  changed_when: false
  failed_when: false

- name: Install Terraform
  shell: tfenv install {{ item }}
  with_items: "{{ terraform_versions }}"
  when: item not in terraform_installed.stdout_lines
