---
- name: Install tfenv
  git:
    repo: "{{ tfenv_repository }}"
    dest: "{{ tfenv_directory }}"
    version: "{{ tfenv_version }}"
    accept_hostkey: yes
    force: yes

- name: Add tfenv initialization to ZSH system profile
  blockinfile:
    block: "{{ lookup('template', 'tfenv-profile.sh.j2') }}"
    dest: /etc/zprofile
    marker_begin: BEGIN TFENV
    marker_end: END TFENV
  become: yes

- name: Check installed Terraform versions
  shell: "{{ tfenv_directory }}/bin/tfenv versions --bare"
  register: terraform_installed
  changed_when: false
  failed_when: false

- name: Install Terraform versions
  shell: "{{ tfenv_directory }}/bin/tfenv install {{ item }}"
  args:
    creates: "~/.tfenv/versions/{{ item }}"
  with_items: "{{ tfenv_terraforms }}"
  when: item not in terraform_installed.stdout_lines

- name: Check if default Terraform version is {{ tfenv_default_terraform }}
  shell: "{{ tfenv_directory }}/bin/tfenv version-name | grep -Fx '{{ tfenv_default_terraform }}'"
  register: tfenv_default_version
  changed_when: false
  failed_when: false

- name: Set default Terraform version to {{ tfenv_default_terraform }}
  shell: "{{ tfenv_directory }}/bin/tfenv use {{ tfenv_default_terraform }}"
  when: tfenv_default_version.rc != 0 and tfenv_default_version.stdout != tfenv_default_terraform

- name: Install additional Terraform packages for Linux
  package:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ terraform_additional_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install additional Terraform packages for macOS
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ terraform_additional_packages }}"
  when: ansible_facts['os_family'] == "Darwin"
