---
- name: Install tgenv
  git:
    repo: "{{ tgenv_repository }}"
    dest: "{{ tgenv_directory }}"
    version: "{{ tgenv_version }}"
    accept_hostkey: yes
    force: yes

- name: Add tgenv initialization to ZSH system profile
  blockinfile:
    block: "{{ lookup('template', 'tgenv-profile.sh.j2') }}"
    dest: /etc/zprofile
    marker_begin: BEGIN tgenv
    marker_end: END tgenv
  become: yes

- name: Check installed Terragrunt versions
  shell: "{{ tgenv_directory }}/bin/tgenv versions --bare"
  register: grunts_installed
  changed_when: false
  failed_when: false

- name: Install Terragrunt versions
  shell: "{{ tgenv_directory }}/bin/tgenv install {{ item }}"
  args:
    creates: "~/.tgenv/versions/{{ item }}"
  with_items: "{{ tgenv_grunts }}"
  when: item not in grunts_installed.stdout_lines

- name: Check if default Terragrunt version is {{ tgenv_default_grunt }}
  shell: "{{ tgenv_directory }}/bin/tgenv version-name | grep -Fx '{{ tgenv_default_grunt }}'"
  register: tgenv_default_version
  changed_when: false
  failed_when: false

- name: Set default Terragrunt version to {{ tgenv_default_grunt }}
  shell: "{{ tgenv_directory }}/bin/tgenv use {{ tgenv_default_grunt }}"
  when: tgenv_default_version.rc != 0 and tgenv_default_version.stdout != tgenv_default_grunt
